creation_timestamp: 1679590648881
current_stage: Production
description: ''
last_updated_timestamp: 1679590725134
name: model_roland_garros
run_id: 8e122d66205b4e7c8c505e8aaf4ba738
run_link: ''
source: file:///workspace/models/corridas2/552394378029237143/8e122d66205b4e7c8c505e8aaf4ba738/artifacts/best_estimator
status: READY
status_message: null
user_id: null
version: 1
